site_name: StashCache Documentation
site_url: https://opensciencegrid.org/stashcache
repo_url: https://github.com/opensciencegrid/stashcache
theme: material

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Install: 'admin/install.md'
- Cache server:
  - 'admin/configure-cache.md'
  - 'admin/configure-cache-auth.md'
  - 'admin/configure-cache-optional.md'
- Origin server:
  - 'admin/configure-origin.md'
- Operations:
  - 'ops/register.md'
  - 'ops/start.md'
  - 'ops/troubleshoot.md'
  - 'ops/redirector.md'
  - 'ops/upgrades.md'

markdown_extensions:
    - admonition
    - markdown_include.include
